### ISSUE TITLE
Feature List Improvements

### ISSUE THREAD

**Issue by idbentley** [jc328/TeamProject#1]
Hello Robinhood Team!

After reviewing your feature list documentation, here is a list of our feedback. Please address these concerns today (Thursday July 9) and send a message in your slack channel when addressed.
 - Add a dedicated feature list page to either your github repo or your wiki.
 - In general these features leave too much to interpretation - add a lot of details about what actions a user can take, and what authorizations are needed to do so. Instead of "Login Page" specify each of the features needed: "User login, signup, profile page, etc."
 - What is a dashboard?  What information is visible there? what types of charts do I expect to see?
 - You should specify the CRUD operations for stocks that you own 
 - Support multiple "fantasy portfolio" which are listing of prospective stocks - there should support all four CRUD operations.
 - You should specify the CRUD operations for adding and manipulating stocks in your fantasy portfolios.
 - What information is visible on a stock detail page?
 - How does search work? Can I only search by company name/ ticker, or can I filter for stocks with recent growth, etc.
 - Add Heroku hosting of site and database as feature
 - Add high quality README.md and documentation as feature
 - Add one or two Bonus / Stretch goals that you will implement if you have time.

Because your feature list is somewhat sparse, you should call a TA to do final review as soon as practical.

**Comment by jc328** [comment]
Completed
