### ISSUE TITLE
Routes Improvements

### ISSUE THREAD

**Issue by idbentley** [jc328/TeamProject#2]
For the sake of this application, we do not need to differentiate between Frontend and Backend routes. Since our applications directly return and render html (as derived from pug templates) instead of returning JSON to be interpreted by a frontend framework (which we will see with React shortly), do not prepend the routes with `/api` and do not separate routes that render html from those that do work (like POSTs, PUTs and DELETEs).

This general feedback means that for example: you should move the signup form: `/signup` into the Users section.  It's route should be `GET /users/new` and it's description: "Renders Sign Up Form". Please apply this pattern to all frontend routes.

Your application should have one *api* route related to search, which should return a JSON response, in order to support the rich search functionality that you've chosen to implement.

## Unnecessary routes
 - I see no reason for you to need `GET /api/users` except for administration (out of scope for this project).  The same note applies for `GET /api/watchlist` I think the watchlists are probably displayed on a users page, and can be brought in through Sequelize associations `include`.
 - You have both `GET /users/:id` and `GET /api/users/:id` for the reasons I stated at the top, you probably only need the first for this project. (this applies to `/stocks/:id` as well).

## Route descriptions
 -  `GET /users/:id` - Returns the consumer to their account page -> "Render the users account page" 

## Missing routes
 - `POST /stocks/add` - this needs a form route, and it could be more RESTful: `GET /stocks/new` and `POST /stocks`
 - I don't see any way to add stocks to a watch list, to remove them, or to otherwise make adjustments to watchlists.
 - I don't see any way to buy/sell shares 
 - I don't see any way to do the rich search functionality that you all described to me yesterday.

It seems like there's some missing functionality here, so please grab a TA after to working through these initial notes.

**Comment by jc328** [comment]
approved via live review - Jul 10th
